from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.config.dependency import get_db, get_current_user
from app.models.user import User

from app.services.inventory_forecasting_service import (
    get_inventory_forecast,
    get_product_inventory_forecast,
    get_recommendation_summary,
)

from app.schemas.inventory_forecasting_schema import (
    InventoryForecastResponse,
    InventoryForecastSummaryResponse,
)


router = APIRouter(
    prefix="/inventory/forecast",
    tags=["Inventory Forecasting"],
)


@router.get(
    "",
    response_model=list[InventoryForecastResponse],
)
def inventory_forecast(
    forecast_days: int = 30,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return inventory forecast and replenishment analysis
    for all active products.
    """

    if forecast_days not in (7, 30, 90):
        raise HTTPException(
            status_code=400,
            detail="forecast_days must be 7, 30, or 90.",
        )

    return get_inventory_forecast(
        db=db,
        company_id=current_user.company_id,
        forecast_days=forecast_days,
    )


@router.get(
    "/recommendations",
    response_model=list[InventoryForecastResponse],
)
def inventory_recommendations(
    forecast_days: int = 30,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return inventory recommendations generated by the
    Task 11 replenishment engine.
    """

    if forecast_days not in (7, 30, 90):
        raise HTTPException(
            status_code=400,
            detail="forecast_days must be 7, 30, or 90.",
        )

    forecasts = get_inventory_forecast(
        db=db,
        company_id=current_user.company_id,
        forecast_days=forecast_days,
    )

    return [
        item
        for item in forecasts
        if (
            item["recommended_reorder_quantity"] > 0
            or item["stock_risk"] != "Healthy"
        )
    ]


@router.get(
    "/recommendations/{product_id}",
    response_model=InventoryForecastResponse,
)
def product_inventory_recommendation(
    product_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return detailed forecast and replenishment analysis
    for a single product.
    """

    result = get_product_inventory_forecast(
        db=db,
        company_id=current_user.company_id,
        product_id=product_id,
    )

    if result is None:
        raise HTTPException(
            status_code=404,
            detail=(
                "Product or inventory information "
                "was not found."
            ),
        )

    return result


@router.get(
    "/summary",
    response_model=InventoryForecastSummaryResponse,
)
def inventory_forecast_summary(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return dynamic Task 11 summary metrics.
    """

    return get_recommendation_summary(
        db=db,
        company_id=current_user.company_id,
    )